"""Build progressive map tiles from your own campaign image."""

from pathlib import Path
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "public/images/campaign-map-source.jpg"
OUTPUT = ROOT / "public/images/map-tiles"
TILE_SIZE = 512


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    # A newly supplied map can have different dimensions. Remove only tiles
    # generated by an earlier run so obsolete levels never remain available.
    for previous_tile in OUTPUT.rglob("*.webp"):
        previous_tile.unlink()
    for folder in sorted((path for path in OUTPUT.rglob("*") if path.is_dir()), key=lambda path: len(path.parts), reverse=True):
        if not any(folder.iterdir()):
            folder.rmdir()
    with Image.open(SOURCE) as original:
        original.load()
        widths = tuple(width for width in (1024, 2048, 4096, original.width) if width <= original.width)
        widths = tuple(dict.fromkeys(widths))
        preview_width = min(1024, original.width)
        preview = original.resize((preview_width, round(original.height * preview_width / original.width)), Image.Resampling.LANCZOS)
        preview.save(OUTPUT / "preview.webp", "WEBP", quality=76, method=6)
        for width in widths:
            height = round(original.height * width / original.width)
            level = original if width == original.width else original.resize((width, height), Image.Resampling.LANCZOS)
            folder = OUTPUT / str(width)
            folder.mkdir(exist_ok=True)
            count = 0
            for y in range(0, height, TILE_SIZE):
                for x in range(0, width, TILE_SIZE):
                    tile = level.crop((x, y, min(x + TILE_SIZE, width), min(y + TILE_SIZE, height)))
                    # High-quality tiles keep small labels legible while loading
                    # only the visible portion of a large map.
                    tile.save(folder / f"{x // TILE_SIZE}-{y // TILE_SIZE}.webp", "WEBP", quality=95, method=6)
                    count += 1
            print(f"{width}x{height}: {count} tiles")


if __name__ == "__main__":
    main()
