import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { BookOpenText, FileText, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import type { DmNoteCategory, DmNotebook, DmNotebookData } from '../shared/types';
import { api, send } from './api';
import { ErrorLine, Modal, Submit } from './components';

export default function DmNotes({notify}:{notify:(value:string)=>void}){
  const [data,setData]=useState<DmNotebookData|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[open,setOpen]=useState<string|null>(null);
  const [editing,setEditing]=useState<DmNotebook|null|undefined>(undefined),[initialCategory,setInitialCategory]=useState(''),[category,setCategory]=useState<DmNoteCategory|null|undefined>(undefined);
  const load=async()=>{try{setData(await api<DmNotebookData>('/dm-notebooks'));setError('');}catch(e){setError((e as Error).message);}};
  useEffect(()=>{load();},[]);
  const visible=useMemo(()=>data?.notes.filter(note=>`${note.title} ${note.body}`.toLowerCase().includes(query.trim().toLowerCase()))||[],[data,query]);
  if(!data)return <section className="notebooks-page"><ErrorLine error={error}/><p className="loading">Відкриваємо нотатки…</p></section>;
  return <section className="notebooks-page" aria-labelledby="dm-notes-title">
    <header className="notebooks-hero"><div><h1 id="dm-notes-title">Нотатки майстра</h1><p>Текстові блокноти для планів, таємниць і підготовки до гри.</p></div><div><span><strong>{data.notes.length}</strong> блокнотів</span><button className="button secondary" onClick={()=>setCategory(null)}><Plus size={16}/>Категорія</button><button className="button primary" onClick={()=>{setInitialCategory('');setEditing(null)}}><Plus size={16}/>Новий блокнот</button></div></header>
    <label className="notebooks-search"><Search size={17}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Знайти в назвах і тексті…"/></label>
    <div className="notebooks-layout"><aside className="notebooks-jump"><span className="nav-label">КАТЕГОРІЇ</span><nav>{data.categories.map(item=><button type="button" onClick={()=>document.getElementById(`dm-note-category-${item.id}`)?.scrollIntoView({behavior:'smooth',block:'start'})} key={item.id}><span>{item.title}</span><small>{visible.filter(note=>note.category_id===item.id).length}</small></button>)}</nav></aside>
      <div className="notebook-groups">{data.categories.map(item=>{const notes=visible.filter(note=>note.category_id===item.id);return <section className="notebook-group" id={`dm-note-category-${item.id}`} key={item.id}><header><div><BookOpenText size={18}/><h2>{item.title}</h2><span>{notes.length}</span></div><button className="icon-button" aria-label={`Редагувати категорію ${item.title}`} onClick={()=>setCategory(item)}><Pencil size={16}/></button></header><div className="notebook-list">{notes.map(note=>{const expanded=open===note.id;return <article className={`notebook-card ${expanded?'expanded':''}`} key={note.id}><button className="notebook-summary" aria-expanded={expanded} onClick={()=>setOpen(expanded?null:note.id)}><FileText size={20}/><span><strong>{note.title}</strong><small>{note.body.trim().slice(0,120)||'Порожній блокнот'}</small></span></button><button className="notebook-edit icon-button" aria-label={`Редагувати ${note.title}`} onClick={()=>{setInitialCategory('');setEditing(note)}}><Pencil size={16}/></button>{expanded&&<div className="notebook-body"><p>{note.body||'Цей блокнот поки порожній.'}</p></div>}</article>})}{notes.length===0&&<p className="notebook-empty">{query?'У цій категорії нічого не знайдено.':'У категорії ще немає блокнотів.'}</p>}</div><button className="notebook-group-add" onClick={()=>{setInitialCategory(item.id);setEditing(null)}}><Plus size={15}/>Новий блокнот</button></section>})}</div>
    </div>
    {editing!==undefined&&<NotebookEditor note={editing||undefined} initialCategoryId={initialCategory} categories={data.categories} close={()=>{setEditing(undefined);setInitialCategory('')}} saved={async(deleted=false)=>{await load();setEditing(undefined);setInitialCategory('');notify(deleted?'Блокнот прибрано':editing?'Блокнот оновлено':'Блокнот створено');}}/>}
    {category!==undefined&&<CategoryEditor category={category||undefined} close={()=>setCategory(undefined)} saved={async()=>{await load();setCategory(undefined);notify(category?'Категорію перейменовано':'Категорію створено');}}/>}
  </section>;
}

function CategoryEditor({category,close,saved}:{category?:DmNoteCategory;close:()=>void;saved:()=>Promise<void>}){
  const [title,setTitle]=useState(category?.title||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <Modal title={category?'Перейменувати категорію':'Нова категорія'} close={close}><form onSubmit={async(event)=>{event.preventDefault();setBusy(true);setError('');try{await send(category?`/dm-note-categories/${category.id}`:'/dm-note-categories',category?'PUT':'POST',{title,version:category?.version});await saved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="field">Назва категорії<input autoFocus required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Наприклад, Наступна сесія"/></label><ErrorLine error={error}/><div className="form-actions"><button type="button" className="button ghost" onClick={close}>Скасувати</button><Submit busy={busy}/></div></form></Modal>;
}

function NotebookEditor({note,initialCategoryId,categories,close,saved}:{note?:DmNotebook;initialCategoryId?:string;categories:DmNoteCategory[];close:()=>void;saved:(deleted?:boolean)=>Promise<void>}){
  const [form,setForm]=useState({category_id:note?.category_id||initialCategoryId||categories[0]?.id||'',title:note?.title||'',body:note?.body||''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await send(note?`/dm-notebooks/${note.id}`:'/dm-notebooks',note?'PUT':'POST',{...form,version:note?.version});await saved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal title={note?'Редагувати блокнот':'Новий блокнот'} close={close} wide><form onSubmit={submit}><div className="two-columns"><label className="field">Категорія<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}>{categories.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label className="field">Назва *<input autoFocus required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Що потрібно підготувати?"/></label><label className="field full">Текст<textarea className="notebook-editor-text" rows={16} maxLength={100000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Пиши звичайним текстом…"/></label></div><ErrorLine error={error}/><div className="form-actions">{note&&<button type="button" className="text-button danger-text" onClick={async()=>{if(!confirm(`Прибрати блокнот «${note.title}»?`))return;setBusy(true);try{await send(`/dm-notebooks/${note.id}`,'DELETE',{version:note.version});await saved(true);}catch(e){setError((e as Error).message);setBusy(false);}}}><Trash2 size={15}/>Прибрати</button>}<button type="button" className="button ghost" onClick={close}>Скасувати</button><Submit busy={busy}>{note?'Зберегти':'Створити блокнот'}</Submit></div></form></Modal>;
}
