import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ChevronDown, CircleHelp, ImagePlus, MapPin, Pencil, Plus, Search, Skull, UserRound, UsersRound } from 'lucide-react';
import type { Npc, NpcCategory, NpcData, NpcStatus } from '../shared/types';
import { api, send } from './api';
import { ErrorLine, Modal, Submit } from './components';

const races=['Ааракокра','Аасімар','Багбір','Кентавр','Чейнджлінг','Драконороджений','Дварф','Ельф','Фея','Фірболг','Генасі','Гіт’янкі','Гітзерай','Гном','Гоблін','Голіаф','Гаренгон','Гобгоблін','Галфлінг','Калаштар','Кенку','Кобольд','Леонін','Людина','Лізардфолк','Локсодон','Мінотавр','Морський ельф','Напівельф','Напіворк','Орк','Оулін','Плазмоїд','Реборн','Сатир','Табаксі','Тіфлінг','Тортл','Три-крін','Тритон','Варфордж','Ведалкен','Вердан','Шадар-кай','Шифтер','Юань-ті','Інша'];
const statusMeta:Record<NpcStatus,{label:string;icon:typeof UserRound}>={alive:{label:'Живий',icon:UserRound},dead:{label:'Мертвий',icon:Skull},missing:{label:'Зниклий',icon:CircleHelp},unknown:{label:'Невідомо',icon:CircleHelp}};

export default function Npcs({notify}:{notify:(value:string)=>void}){
  const [data,setData]=useState<NpcData|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<'all'|NpcStatus>('all');
  const [editing,setEditing]=useState<Npc|null|undefined>(undefined),[newNpcCategory,setNewNpcCategory]=useState(''),[category,setCategory]=useState<NpcCategory|null|undefined>(undefined),[open,setOpen]=useState<string|null>(null);
  const load=async()=>{try{setData(await api<NpcData>('/npcs'));setError('');}catch(e){setError((e as Error).message);}};
  useEffect(()=>{load();},[]);
  const visible=useMemo(()=>data?.npcs.filter(n=>status==='all'||n.status===status).filter(n=>`${n.name} ${n.race} ${n.role} ${n.location} ${n.description}`.toLowerCase().includes(query.trim().toLowerCase()))||[],[data,query,status]);
  if(!data)return <section className="npc-page"><ErrorLine error={error}/>{error?<button className="button secondary" onClick={load}>Спробувати ще раз</button>:<p className="loading">Відкриваємо каталог NPC…</p>}</section>;
  return <section className="npc-page" aria-labelledby="npc-title">
    <header className="npc-hero"><div><h1 id="npc-title">NPC</h1><p>Імена, ролі, зв’язки та останні відомі місця.</p></div><div className="npc-hero-actions"><span><strong>{data.npcs.length}</strong> персонажів</span><button className="button secondary" onClick={()=>setCategory(null)}><Plus size={16}/>Категорія</button><button className="button primary" onClick={()=>{setNewNpcCategory('');setEditing(null)}}><Plus size={16}/>Додати NPC</button></div></header>
    <div className="npc-toolbar"><label className="npc-search"><Search size={17}/><input type="search" placeholder="Знайти за ім’ям, расою або місцем…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="npc-status-filter"><span>Стан</span><select value={status} onChange={e=>setStatus(e.target.value as 'all'|NpcStatus)}><option value="all">Усі</option>{Object.entries(statusMeta).map(([value,item])=><option key={value} value={value}>{item.label}</option>)}</select></label></div>
    <div className="npc-layout"><aside className="npc-jump"><span className="nav-label">КАТЕГОРІЇ</span><nav>{data.categories.map(c=>{const count=visible.filter(n=>n.category_id===c.id).length;return <button type="button" key={c.id} onClick={()=>document.getElementById(`npc-category-${c.id}`)?.scrollIntoView({behavior:'smooth',block:'start'})}><span>{c.title}</span><small>{count}</small></button>})}</nav></aside>
      <div className="npc-groups">{data.categories.map(c=>{const items=visible.filter(n=>n.category_id===c.id);const addToCategory=()=>{setNewNpcCategory(c.id);setEditing(null)};return <section className="npc-group" id={`npc-category-${c.id}`} key={c.id}><header><div><UsersRound size={18}/><h2>{c.title}</h2><span>{items.length}</span></div><button className="icon-button" aria-label={`Редагувати категорію ${c.title}`} onClick={()=>setCategory(c)}><Pencil size={16}/></button></header>{items.length?<div className="npc-list">{items.map(n=>{const meta=statusMeta[n.status],StatusIcon=meta.icon,expanded=open===n.id;return <article className={`npc-row ${expanded?'expanded':''}`} key={n.id}><button className="npc-summary" aria-expanded={expanded} onClick={()=>setOpen(expanded?null:n.id)}>{n.portrait?<img src={n.portrait} alt=""/>:<span className="npc-avatar"><UserRound size={24}/></span>}<span className="npc-identity"><strong>{n.name}</strong><small>{[n.race,n.role].filter(Boolean).join(' · ')||'Опис ще не додано'}</small></span>{n.location&&<span className="npc-location"><MapPin size={14}/>{n.location}</span>}<span className={`npc-status ${n.status}`}><StatusIcon size={13}/>{meta.label}</span><ChevronDown className="npc-chevron" size={17}/></button><button className="npc-edit icon-button" aria-label={`Редагувати ${n.name}`} onClick={()=>{setNewNpcCategory('');setEditing(n)}}><Pencil size={16}/></button>{expanded&&<div className="npc-detail"><div>{n.portrait?<img src={n.portrait} alt={`Портрет ${n.name}`}/>:<span className="npc-detail-placeholder"><UserRound size={42}/></span>}</div><p>{n.description||'Докладний опис цього персонажа ще не додано.'}</p></div>}</article>})}</div>:<div className="npc-empty"><p>{query||status!=='all'?'У цій категорії нічого не знайдено.':'У категорії ще немає персонажів.'}</p></div>}<button className="npc-group-add" onClick={addToCategory}><Plus size={15}/>Додати NPC</button></section>})}</div>
    </div>
    {editing!==undefined&&<NpcEditor npc={editing||undefined} initialCategoryId={newNpcCategory} categories={data.categories} close={()=>{setEditing(undefined);setNewNpcCategory('')}} saved={async()=>{await load();setEditing(undefined);setNewNpcCategory('');notify(editing?'NPC оновлено':'NPC додано');}}/>}
    {category!==undefined&&<CategoryEditor category={category||undefined} close={()=>setCategory(undefined)} saved={async()=>{await load();setCategory(undefined);notify(category?'Категорію перейменовано':'Категорію додано');}}/>}
  </section>;
}

function CategoryEditor({category,close,saved}:{category?:NpcCategory;close:()=>void;saved:()=>Promise<void>}){
  const [value,setValue]=useState(category?.title||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <Modal title={category?'Перейменувати категорію':'Нова категорія'} close={close}><form onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError('');try{await send(category?`/npc-categories/${category.id}`:'/npc-categories',category?'PUT':'POST',{title:value,version:category?.version});await saved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="field">Назва категорії<input autoFocus required maxLength={200} value={value} onChange={e=>setValue(e.target.value)} placeholder="Наприклад, Невервінтер"/></label><ErrorLine error={error}/><div className="form-actions"><button type="button" className="button ghost" onClick={close}>Скасувати</button><Submit busy={busy}/></div></form></Modal>;
}

function NpcEditor({npc,initialCategoryId,categories,close,saved}:{npc?:Npc;initialCategoryId?:string;categories:NpcCategory[];close:()=>void;saved:()=>Promise<void>}){
  const [form,setForm]=useState({category_id:npc?.category_id||initialCategoryId||categories[0]?.id||'',name:npc?.name||'',race:npc?.race||'',role:npc?.role||'',location:npc?.location||'',status:npc?.status||'unknown' as NpcStatus,description:npc?.description||'',portrait:npc?.portrait||''});
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const field=(name:keyof typeof form,value:string)=>setForm(f=>({...f,[name]:value}));
  const readPortrait=(file?:File)=>{if(!file)return;if(file.size>600000){setError('Зображення завелике. Максимум — 600 КБ.');return;}const reader=new FileReader();reader.onload=()=>{field('portrait',String(reader.result));setError('');};reader.readAsDataURL(file);};
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await send(npc?`/npcs/${npc.id}`:'/npcs',npc?'PUT':'POST',{...form,version:npc?.version});await saved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal title={npc?'Редагувати NPC':'Новий NPC'} close={close} wide><form className="npc-editor" onSubmit={submit}><div className="npc-editor-grid"><div className="npc-portrait-field">{form.portrait?<img src={form.portrait} alt="Попередній перегляд портрета"/>:<span><ImagePlus size={31}/><small>Портрет</small></span>}<label className="button secondary">{form.portrait?'Замінити':'Додати фото'}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>readPortrait(e.target.files?.[0])}/></label>{form.portrait&&<button type="button" className="text-button" onClick={()=>field('portrait','')}>Прибрати</button>}</div><div className="npc-fields"><div className="two-columns"><label className="field full">Ім’я *<input autoFocus required maxLength={200} value={form.name} onChange={e=>field('name',e.target.value)} placeholder="Ім’я або прізвисько"/></label><label className="field">Категорія<select value={form.category_id} onChange={e=>field('category_id',e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="field">Стан<select value={form.status} onChange={e=>field('status',e.target.value)}>{Object.entries(statusMeta).map(([value,item])=><option key={value} value={value}>{item.label}</option>)}</select></label><label className="field">Раса<input list="npc-races" maxLength={100} value={form.race} onChange={e=>field('race',e.target.value)} placeholder="Почни вводити…"/><datalist id="npc-races">{races.map(r=><option key={r}>{r}</option>)}</datalist></label><label className="field">Роль або заняття<input maxLength={200} value={form.role} onChange={e=>field('role',e.target.value)} placeholder="Торговець, маг, союзник…"/></label><label className="field full">Останнє відоме місце<input maxLength={200} value={form.location} onChange={e=>field('location',e.target.value)} placeholder="Місто, фракція або локація"/></label><label className="field full">Загальний опис<textarea rows={6} maxLength={20000} value={form.description} onChange={e=>field('description',e.target.value)} placeholder="Зовнішність, характер, зв’язки та важливі подробиці…"/></label></div></div></div><ErrorLine error={error}/><div className="form-actions"><button type="button" className="button ghost" onClick={close}>Скасувати</button><Submit busy={busy}>{npc?'Зберегти зміни':'Створити NPC'}</Submit></div></form></Modal>;
}
